
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/proj-courses-f24-03
owner: ucsb-cs156-f24
repo_name: proj-courses-f24-03
pull_requests: [{"author":{"id":"U_kgDOBs6HEA","is_bot":false,"login":"chloecweng","name":""},"headRefName":"chloe-issue1","number":12,"title":"Suppress Warning","url":"https://github.com/ucsb-cs156-f24/proj-courses-f24-03/pull/12"}]
